import { NextRequest, NextResponse } from 'next/server'
import { decryptSession } from '@/lib/auth'

export const dynamic = 'force-dynamic'

export async function POST(request: NextRequest) {
  try {
    const { pin, sessionId, sessionToken } = await request.json()
    // Decrypt the session token that was generated by the sender and carried
    // inside the viewer link — no server-side state needed at all.
    const session = await decryptSession(sessionToken)
    if (!session) return NextResponse.json({ valid: false })
    const valid =
      typeof pin === 'string' && pin === session.pin &&
      typeof sessionId === 'string' && sessionId === session.sessionId
    return NextResponse.json({ valid })
  } catch {
    return NextResponse.json({ valid: false }, { status: 400 })
  }
}
